#!/usr/bin/env python
import serial
import struct

ser = serial.Serial('/dev/ttyACM0')

ser.write(b'Get Meter Data')

voltage = struct.unpack('f', ser.read(4))[0]
current = struct.unpack('f', ser.read(4))[0]
power = struct.unpack('f', ser.read(4))[0]
voltageDP = struct.unpack('f', ser.read(4))[0]
voltageDM = struct.unpack('f', ser.read(4))[0]

print("Voltage:", voltage, "current:", current, "power:", power, "voltageDP:", voltageDP, "voltageDM:", voltageDM)

ser.close()
